version: "3.6"

services:
  hub:
    image: selenium/hub
    ports:
      - "4444:4444"
    environment:
      GRID_MAX_SESSION: 16
      GRID_BROWSER_TIMEOUT: 3000
      GRID_TIMEOUT: 30

  database:
    image: "postgres" # use latest official postgres version
    env_file:
      - database.env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts downvolumes:

  chrome:
    image: selenium/node-chrome
    container_name: web-automation_chrome
    depends_on:
      - hub
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
      NODE_MAX_SESSION: 20
      NODE_MAX_INSTANCES: 20
    volumes:
      - /dev/shm:/dev/shm
#      - browser-downloads:/dev/downloads
    ports:
      - "9011:5900"
    links:
      - hub

  firefox:
    image: selenium/node-firefox
    container_name: web-automation_firefox
    depends_on:
      - hub
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
      NODE_MAX_SESSION: 20
      NODE_MAX_INSTANCES: 20
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "9012:5900"
    links:
      - hub

volumes:
  browser-downloads:
    name: browser-downloads2
    driver_opts:
      type: none
      device: ./files
      o: bind
  database-data: # named volumes can be managed easier using docker-compose
    name: database-data2
    driver_opts:
      type: none
      device: ./database
      o: bind