"""added field created

Revision ID: 725d8512f46b
Revises: 0037276b2d8f
Create Date: 2020-12-14 17:23:02.941674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "725d8512f46b"
down_revision = "0037276b2d8f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("company", sa.Column("created", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("company", "created")
    # ### end Alembic commands ###
